name: NeoCanvas

options:
  bundleIdPrefix: com.neoworksuite
  deploymentTarget:
    iOS: "15.0"

configs:
  Debug: debug
  Release: release

settings:
  base:
    SWIFT_VERSION: "6.0"
    ENABLE_USER_SCRIPT_SANDBOXING: NO

targets:

  NeoCanvas:

    type: application
    platform: iOS

    deploymentTarget: "15.0"

    sources:
      - path: NeoCanvas

    configFiles:
      Debug: Configuration/Config.xcconfig
      Release: Configuration/Config.xcconfig

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.neoworksuite.neocanvas
        PRODUCT_NAME: NeoCanvas
        TARGETED_DEVICE_FAMILY: "1,2"
        CODE_SIGN_STYLE: Automatic
        ENABLE_USER_SCRIPT_SANDBOXING: NO
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: NeoCanvas
        INFOPLIST_KEY_UILaunchScreen_Generation: YES

    preBuildScripts:

      - name: Compile NeoCanvas Kotlin Framework

        script: |
          if [ "YES" = "$OVERRIDE_KOTLIN_BUILD_IDE_SUPPORTED" ]; then
            echo "Skipping duplicate Kotlin framework build"
            exit 0
          fi

          cd "$SRCROOT/.."

          ./gradlew :ui:embedAndSignAppleFrameworkForXcode

        basedOnDependencyAnalysis: false